redhat-developer/vscode-project-initializer

- src/extension.ts
> Remove extra https:// prefix in extension.ts urls

- CHANGELOG.md
- README.md
- package.json
- src/Catalog.ts
> Generate .vscode recommandation file(s)

- CHANGELOG.md
- package.json
- src/extension.ts
- src/test/extension.runtimes.test.ts
- src/test/extension.test.ts
it will be easier to review after https://github.com/fabric8-launcher/launcher-vscode-extension/pull/23 has been merged
> 24 specific command for each runtime

- .vscode/extensions.json
> Update TSLint recommendation

- src/extension.ts
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
> Follow TSLint recommendations

- CHANGELOG.md
- README.md
- package.json
> Prepare for 0.0.9

- package.json
> Bump to 0.0.10

- Jenkinsfile
> Archive stable versions in a folder

- README.md
> Fix CI build statuses

- Jenkinsfile
> Fix GitHub repo in Jenkinsfile

- package.json
- src/test/index.ts
- src/test/runTest.ts
> Switch to new VSCode test infrastructure

- Jenkinsfile
> Archive source tarball when generating release

- Jenkinsfile
> Fix Jenkinsfile syntax

- Jenkinsfile
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
> Fix archiving artfefacts in Jenkins when publishing stable build #40

- README.md
> Add Marketplace badges

- LICENSE
- package.json
- src/ui-test/allTestsSuite.ts
> Add license file EPL 2.0

- src/ui-test/baseExtensionTest.ts
- src/ui-test/camelProjectCreateTest.ts
- src/ui-test/camelProjectOfferingTest.ts
- src/ui-test/commandPaletteOptionsTest.ts
- src/ui-test/common/commonUtils.ts
> Fix compilation errors in UI tests

- Jenkinsfile
> Add open-vsx.org publication

- Jenkinsfile
> Fix node version

- package.json
> Prepare for 0.0.11

- Jenkinsfile
https://gitlab.mw.lab.eng.bos.redhat.com/dev-platform/cci-config/issues/8
> Use .git suffix to have polling cron working dev-platform/cci-config#8

- package.json
- src/ui-test/camelProjectCreateTest.ts
- src/ui-test/common/commonUtils.ts
> Update extester, fix tests

- .github/workflows/CI.yml
> Add GitHub workflow

- src/ui-test/camelProjectCreateTest.ts
> fix notification handling after ElementNotVisibleError

- .github/workflows/CI.yml
> chore: add MacOS workflow

- Jenkinsfile
- README.md
- USAGE_DATA.md
- package-lock.json
- package.json
- src/extension.ts
- src/telemetry.ts
- src/test/runTest.ts
- src/test/telemetry.test.ts
> Add telemetry

- README.md
- package.json
> Prepare for 0.1.0

- Jenkinsfile
> chore: Use single node in Jenkinsfile

- README.md
- package-lock.json
- package.json
- src/test/runTest.ts
> refactor: Remove dependency to vscode-commons

- src/extension.ts
- src/telemetry.ts
> fix: Use proper telemetry API

- README.md
- package-lock.json
- package.json
> Prepare for 0.2.1

- .github/workflows/CI.yml
- .gitignore
- Jenkinsfile
- package-lock.json
- package.json
- src/test/index.ts
- src/ui-test/camelProjectCreateTest.ts
- tsconfig.json
Signed-off-by: Dominik Jelinek <djelinek@redhat.com>
> Update test dependencies and fix UI tests

- CHANGELOG.md
- README.md
- package.json
> feat: deprecate extension

- Jenkinsfile
> chore: Fix nodejs runtime used in Jenkinsfile

- .github/workflows/CI.yml
- package.json
- src/extension.ts
- src/ui-test/camelProjectCreateTest.ts
- src/ui-test/common/commonUtils.ts
> Debugging vscode ui tests

- Jenkinsfile
> Switch to SFTP

- Jenkinsfile
> fix: add OpenVSX single deployment
